version: 2
jobs:
        build:
                - image circleci/python:3.6.1
        steps:
                - checkout
                - run:
                        name: Create virtualenv
                        command: python -m venv myenv
                - run:
                        name: Install pycards and test
                        command: |
                                . myenv/bin/activate
                                pip install .
                                nose2
